server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  main:
    allow-bean-definition-overriding: true

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Yugioh@04112002